-- --------------------------------------------------------------------------------------------------
-- ---- EDATOS-5210 - Modificar el campo COLL_METHOD
-- ---- Nuevos campos en la tabla TB_LIS_COLL_METHODS con el orden de visualización
-- --------------------------------------------------------------------------------------------------

ALTER TABLE TB_LIS_COLL_METHODS ADD COLUMN VISUALISATION_ORDER INTEGER;
ALTER TABLE TB_LIS_COLL_METHODS ADD COLUMN HIERARCHY_LEVEL INTEGER NOT NULL DEFAULT 0;

UPDATE TB_LIS_COLL_METHODS SET VISUALISATION_ORDER = -1 WHERE IDENTIFIER = 'AUTOENUMERACION';
UPDATE TB_LIS_COLL_METHODS SET VISUALISATION_ORDER = -2 WHERE IDENTIFIER = 'ENTREVISTA_DIRECTA';
UPDATE TB_LIS_COLL_METHODS SET VISUALISATION_ORDER = -3 WHERE IDENTIFIER = 'CONVERSACION_TELEFONO';
UPDATE TB_LIS_COLL_METHODS SET VISUALISATION_ORDER = -4 WHERE IDENTIFIER = 'TRANSCRIPCION_DOCUMENTO';
UPDATE TB_LIS_COLL_METHODS SET VISUALISATION_ORDER = -5 WHERE IDENTIFIER = 'OBSERVACION_DIRECTA';
UPDATE TB_LIS_COLL_METHODS SET VISUALISATION_ORDER = -6 WHERE IDENTIFIER = 'FORMAS_MIXTAS';
UPDATE TB_LIS_COLL_METHODS SET VISUALISATION_ORDER = -7 WHERE IDENTIFIER = 'OTRAS';
UPDATE TB_LIS_COLL_METHODS SET VISUALISATION_ORDER = -8 WHERE IDENTIFIER = 'NO_APLICABLE';
UPDATE TB_LIS_COLL_METHODS SET VISUALISATION_ORDER = -9 WHERE IDENTIFIER = 'INDETERMINADA';


ALTER TABLE TB_LIS_COLL_METHODS ALTER COLUMN VISUALISATION_ORDER SET NOT NULL;

COMMIT;

