-- --------------------------------------------------------------------------------------------------
-- ---- EDATOS-5210 - Modificar el campo COLL_METHOD
-- ---- Modificar tabla TB_LIS_COLL_METHODS para que tenga una lista de valores categorizados.
-- --------------------------------------------------------------------------------------------------

/*

--1 Añadir extensión si no existe en el esquema extensions
--1.1) Ver si existe en esquema extensions
SELECT *
FROM pg_extension e
JOIN pg_namespace n ON e.extnamespace = n.oid
WHERE e.extname = 'uuid-ossp'
  AND n.nspname = 'extensions';

-- 1.2)  Si no existe crear en ese esquema

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;

*/

-- NOTA. Cada bloque DO $$ ... END $$ debe ejecutarse en secuencia. Si la BD está con autocommit, asegúrarase de ejecutar este script en el orden mostrado.
--------------------------------------------------------------------------------------------------------------------------


--!! ATENCIÓN!!!. PARA EJECUTAR ESTE SCRIPT PRIMERO SE HA DEBIDO EJECUTAR EL SCRIPT 20251006_1-update_tb_lis_coll_method.sql

-- 01 - Recogida directa de datos estadísticos
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Recogida directa de datos estadísticos', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Direct statistical data collection', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Recollida directa de dades estadístiques', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '01', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1, 0);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 01_01 - Obtención mediante censo o enumeración completa
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtención de datos estadísticos mediante censo o enumeración completa', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Data collection via census or complete enumeration', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Obtenció mitjançant cens o enumeració completa',
                'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '01_01', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 2, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 01_02 - Obtención mediante enumeración por muestreo
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtención de datos estadísticos mediante enumeración por muestreo', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Data collection via sampling enumeration', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Obtenció mitjançant enumeració per mostreig', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '01_02', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 3, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 01_03 - Obtención en forma combinada de censo y muestreo
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtención de datos estadísticos en forma combinada de censo y muestreo', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Data collection via combined census and sampling', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Obtenció en forma combinada de cens i mostreig', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '01_03', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 4, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 01_04 - Obtención mediante sondeos de opinión
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Obtención de datos mediante sondeos de opinión', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Data collection via opinion surveys', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Obtenció mitjançant sondejos d''opinió', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '01_04', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 5, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 02 - Utilización de datos administrativos
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Utilización de datos administrativos', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Use of administrative data', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Ús de dades administratives', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '02', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 6, 0);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 02_01 - Obtención mediante enumeración completa de datos administrativos originales
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtención mediante enumeración completa de datos administrativos originales', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Collection via full enumeration of original administrative data',
                'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtenció mitjançant enumeració completa de dades administratives originals', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '02_01', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 7, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 02_02 - Obtención mediante formulario estadístico individual con base en un acto administrativo
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtención mediante formulario estadístico individual con base en un acto administrativo',
                'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Collection via individual statistical form based on an administrative act', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtenció mitjançant formulari estadístic individual basat en un acte administratiu',
                'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '02_02', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 8, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 02_03 - Obtención mediante elaboración de resúmenes estadísticos con base en datos administrativos
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtención mediante elaboración de resúmenes estadísticos con base en datos administrativos',
                'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Collection via statistical summaries based on administrative data', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtenció mitjançant elaboració de resums estadístics basats en dades administratives',
                'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '02_03', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 9, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 02_04 - Obtención mediante enumeración por muestreo de datos administrativos
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtención mediante enumeración por muestreo de datos administrativos', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Collection via sampling of administrative data', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtenció mitjançant enumeració per mostreig de dades administratives', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '02_04', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 10, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 03 - Utilización conjunta de datos estadísticos y administrativos
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Utilización conjunta de datos estadísticos y administrativos', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Combined use of statistical and administrative data', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Ús conjunt de dades estadístiques i administratives',
                'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '03', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 11, 0);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 04 - Utilización de resultados estadísticos
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Utilización de resultados estadísticos', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Use of statistical results', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Ús de resultats estadístics', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '04', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 12, 0);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 04_01 - Obtención de estadísticas derivadas de otros resultados estadísticos
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtención de estadísticas derivadas de otros resultados estadísticos', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Collection of derived statistics from other statistical results',
                'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Obtenció d''estadístiques derivades d''altres resultats estadístics', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '04_01', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 13, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 04_02 - Recopilación de resultados estadísticos propios o ajenos
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Recopilación de resultados estadísticos propios o ajenos', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Compilation of own or external statistical results', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Recopilació de resultats estadístics propis o aliens',
                'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '04_02', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 14, 1);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 05 - Utilización de bases de datos privadas
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Utilización de bases de datos privadas', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Use of private databases', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Ús de bases de dades privades', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '05', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 15, 0);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 06 - Utilización conjunta de datos estadísticos y bases de datos privadas
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Utilización conjunta de datos estadísticos y bases de datos privadas', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Combined use of statistical data and private databases', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'),
                'Ús conjunt de dades estadístiques i bases de dades privades', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '06', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 16, 0);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 07 - Otras formas de obtención de datos
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Otras formas de obtención de datos', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Other data collection methods', 'en',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Altres formes d''obtenció de dades', 'ca',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '07', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 17, 0);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 08 - No aplicable
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'No aplicable', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Not applicable', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'No aplicable', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '08', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 18, 0);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;

-- 9 - Aún no determinada
DO
$$
    BEGIN
        INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Aún no determinada', 'es',
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Not yet determined', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'),
                1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
        VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Encara no determinada', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'),
                1);
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

        INSERT INTO TB_LIS_COLL_METHODS (ID, IDENTIFIER, UUID, VERSION, DESCRIPTION, VISUALISATION_ORDER,
                                         HIERARCHY_LEVEL)
        VALUES (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'), '09', extensions.uuid_generate_v4(), 0,
                GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 19, 0);

        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';
        UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';
    END
$$;