-- --------------------------------------------------------------------------------------------------
-- --------------------------------------  SOLO PARA IBESTAT  ---------------------------------------
-- --------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------
-- EDATOS-5212  Modificar los campo COST_BURDEN, COST y añadir un nuevo campo COST_DETAIL
--
--     Se actualizan los valores en BBDD según la lista del IBESTAT
--
--     La lista de valores del COST para el IBESTAT es esta:
--          Irrelevante
--          Bajo (igual o inferior a 20.000€)
--          Medio (entre 20.001€ y 100.000€)
--          Alto (entre 100.001€ y 500.000€)
--          Muy alto (más de 500.001€)
-- --------------------------------------------------------------------------------------------------



DO $$
BEGIN

-- ===========================================================
-- Irrelevante/MUY_BAJO
-- ===========================================================

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Irrelevante', 'es',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Irrelevant', 'en',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Irrellevant', 'ca',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


UPDATE TB_LIS_COSTS
SET DESCRIPTION = (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS)
WHERE IDENTIFIER = 'MUY_BAJO';

END $$;

DO $$
BEGIN

-- ===========================================================
-- Bajo
-- ===========================================================
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Bajo (igual o inferior a 20.000€)', 'es',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Low (equal to or below €20,000)', 'en',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Baix (igual o inferior a 20.000€)', 'ca',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

UPDATE TB_LIS_COSTS
SET DESCRIPTION = (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS)
WHERE IDENTIFIER = 'BAJO';

END $$;

DO $$
BEGIN

-- ===========================================================
-- Medio
-- ===========================================================
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Medio (entre 20.001€ y 100.000€)', 'es',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Medium (between €20,001 and €100,000)', 'en',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Mitjà (entre 20.001€ i 100.000€)', 'ca',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


UPDATE TB_LIS_COSTS
SET DESCRIPTION = (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS)
WHERE IDENTIFIER = 'MEDIO';

END $$;

DO $$
BEGIN

-- ===========================================================
-- Alto
-- ===========================================================
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Alto (entre 100.001€ y 500.000€)', 'es',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'High (between €100,001 and €500,000)', 'en',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Alt (entre 100.001€ i 500.000€)', 'ca',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


UPDATE TB_LIS_COSTS
SET DESCRIPTION = (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS)
WHERE IDENTIFIER = 'ALTO';

END $$;

DO $$
BEGIN

-- ===========================================================
-- Muy alto
-- ===========================================================
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Muy alto (más de 500.001€)', 'es',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';


INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Very high (over €500,001)', 'en',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION)
VALUES (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Molt alt (més de 500.001€)', 'ca',
        (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS), 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

UPDATE TB_LIS_COSTS
SET DESCRIPTION = (SELECT MAX(ID) FROM TB_INTERNATIONAL_STRINGS)
WHERE IDENTIFIER IN ('MUY_ALTO', 'MUY_ATO');

END $$;

COMMIT;