<%@page import="org.siemac.metamac.core.common.util.swagger.SwaggerUtils"%>
<%@page import="java.util.ResourceBundle"%>
<%@page import="org.siemac.metamac.statistical.operations.web.external.MessagesResourceBundle"%>
<%@page import="org.siemac.metamac.core.common.util.InternationalizationUtils"%>
<%@page pageEncoding="UTF-8"%>
<%
    String locale = InternationalizationUtils.getInstance().getCurrentLocale(request);
    MessagesResourceBundle messagesResource = new MessagesResourceBundle(locale);
    pageContext.setAttribute("msg", messagesResource);

%>
{
   "swagger":"2.0",
   "info":{
      "description":"${msg['api.doc.swagger.description']}",
      "version":"1.0",
      "title":"${msg['api.doc.swagger.title']}"
   },
   "host":"<%=SwaggerUtils.getApiBaseURLForSwagger()%>",
   "schemes":[

   ],
   "tags":[
      {
         "name":"${msg['api.doc.swagger.tag.families']}",
         "description":""
      },
      {
         "name":"${msg['api.doc.swagger.tag.operations']}",
         "description":""
      },
      {
         "name":"${msg['api.doc.swagger.tag.auxiliaryValueTables']}",
         "description":""
      }
   ],
   "definitions":{
      "ClassSystems":{
         "type":"object",
         "title":"ClassSystems",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "classSystem":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Clasificaciones usadas en la instancia de la operación estadística"
      },
      "CollMethods":{
         "type":"object",
         "title":"CollMethods",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "collMethod":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Valores aceptados para los métodos de recolección de los datos"
      },
      "Costs":{
         "type":"object",
         "title":"Costs",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "cost":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Valores aceptados para los tipos de costes asociados a la operación"
      },
      "DataSharings":{
         "type":"object",
         "title":"DataSharings",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "dataSharing":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  }
               }
            }
         ],
         "description":"Acuerdos y convenios existentes entre organizaciones productoras de datos para la coordinación y compartición de los mismos. "
      },
      "Families":{
         "type":"object",
         "title":"Families",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "family":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listado de familias en las que se agrupan las diferentes operaciones estadísticas"
      },
      "Family":{
         "type":"object",
         "title":"Family",
         "allOf":[
            {
               "properties":{
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.kind']}",
                     "type":"string"
                  },
                  "acronym":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.family.properties.acronym']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "childLinks":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.childLinks']}",
                     "$ref":"#/definitions/ChildLinks"
                  },
                  "description":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.family.properties.description']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.id']}",
                     "type":"string"
                  },
                  "inventoryDate":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.family.properties.inventoryDate']}",
                     "type":"string"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.family.properties.name']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "parentLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.parentLink']}",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "selfLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.selfLink']}",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "urn":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.urn']}",
                     "type":"string"
                  }
               }
            }
         ],
         "description":"Familia de operaciones estadísticas"
      },
      "FreqColls":{
         "type":"object",
         "title":"FreqColls",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "freqColl":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Frecuencias de recolección de los datos"
      },
      "GeographicGranularities":{
         "type":"object",
         "title":"GeographicGranularities",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "geographicGranularity":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Granularidades geográficas"
      },
      "InformationSuppliers":{
         "type":"object",
         "title":"InformationSuppliers",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "informationSupplier":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Organizaciones obligadas a suministrar información para la elaboración de la operación estadística"
      },
      "Instance":{
         "type":"object",
         "title":"Instance",
         "allOf":[
            {
               "properties":{
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.kind']}",
                     "type":"string"
                  },
                  "accuracyOverall":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.accuracyOverall']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "acronym":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.acronym']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "adjustment":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.adjustment']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "seasonalAdjustment":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.seasonalAdjustment']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "basePeriod":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.basePeriod']}",
                     "type":"string"
                  },
                  "childLinks":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.childLinks']}",
                     "$ref":"#/definitions/ChildLinks"
                  },
                  "classSystems":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.classSystems']}",
                     "$ref":"#/definitions/ClassSystems"
                  },
                  "classSystemsDescription":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.classSystemsDescription']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "coherInternal":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.coherInternal']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "coherNationalAccounts":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.coherInternal.coherNationalAccounts']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "coherSubanualAnual":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.coherInternal.coherSubanualAnual']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "coherXDom":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.coherXDom']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "collMethod":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.collMethod']}",
                     "$ref":"#/definitions/Item"
                  },
                  "comment":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.comment']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "completeness":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.completeness']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "coverageError":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.coverageError']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "dataCompilation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.dataCompilation']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "dataDescription":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.dataDescription']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "dataValidation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.dataValidation']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "docMethod":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.docMethod']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "freqColls":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.freqColls']}",
                     "$ref":"#/definitions/FreqColls"
                  },
                  "geographicComparability":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.geographicComparability']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "geographicGranularity":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.geographicGranularity']}",
                     "$ref":"#/definitions/GeographicGranularities"
                  },
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.id']}",
                     "type":"string"
                  },
                  "informationSuppliers":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.informationSuppliers']}",
                     "$ref":"#/definitions/InformationSuppliers"
                  },
                  "inventoryDate":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.inventoryDate']}",
                     "type":"string"
                  },
                  "measurementError":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.inventoryDate.measurementError']}",
                     "$ref":"#/definitions/Measures"
                  },
                  "measures":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.measures']}",
                     "$ref":"#/definitions/Measures"
                  },
                  "modelError":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.modelError']}",
                     "$ref":"#/definitions/Measures"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.name']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "nonResponseError":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.nonResponseError']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "nonsamplingErr":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.nonsamplingErr']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "parentLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.parentLink']}",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "predecessor":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.predecessor']}",
                     "$ref":"#/definitions/Resource"
                  },
                  "processingError":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.processingError']}",
                     "$ref":"#/definitions/Resource"
                  },
                  "punctuality":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.punctuality']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "qualityAssmnt":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.qualityAssmnt']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "qualityAssure":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.qualityAssure']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "qualityDoc":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.qualityDoc']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "samplingErr":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.samplingErr']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "selfLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.selfLink']}",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "statConcDefs":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.statConcDefs']}",
                     "$ref":"#/definitions/StatConcDefs"
                  },
                  "statConcDefsDescription":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.statConcDefsDescription']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "statisticalOperation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.statisticalOperation']}",
                     "$ref":"#/definitions/Resource"
                  },
                  "statisticalOperationSource":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.statisticalOperationSource']}",
                     "$ref":"#/definitions/Item"
                  },
                  "statisticalPopulation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.statisticalPopulation']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "statisticalUnits":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.statisticalUnits']}",
                     "$ref":"#/definitions/StatisticalUnits"
                  },
                  "successor":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.successor']}",
                     "$ref":"#/definitions/Resource"
                  },
                  "temporalComparability":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.temporalComparability']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "temporalGranularity":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.temporalGranularity']}",
                     "$ref":"#/definitions/TemporalGranularities"
                  },
                  "timeliness":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.timeliness']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "urn":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.urn']}",
                     "type":"string"
                  },
                  "userNeeds":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.userNeeds']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "userSat":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.instance.properties.userSat']}",
                     "$ref":"#/definitions/InternationalString"
                  }
               }
            }
         ],
         "description":"La instancia de operación estadística es cada una de las realizaciones de una misma operación estadística. Las instancias pueden ser de dos tipos: SERIE o SECCIÓN. Las instancias de tipo serie proveen información de una serie temporal completa y la instancia acaba cuando se produce una rotura de la serie. Las instancias de tipo sección proveen información de un único instante de tiempo"
      },
      "InstanceTypes":{
         "type":"object",
         "title":"InstanceTypes",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "instanceType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Tipos de instancias"
      },
      "Instances":{
         "type":"object",
         "title":"Instances",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "instance":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listados de instancias de operaciones estadísticas"
      },
      "LegalActs":{
         "type":"object",
         "title":"LegalActs",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "legalActs":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  }
               }
            }
         ],
         "description":"Leyes u otro tipo de convenios (formales o informales) que otorgan reponsabilidad y autoridad al organismo para la recolección, procesado y diseminación de la estadística"
      },
      "Measures":{
         "type":"object",
         "title":"Measures",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "measure":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Unidades en las que se miden los datos"
      },
      "OfficialityTypes":{
         "type":"object",
         "title":"OfficialityTypes",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "officialityType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Tipos de oficialidad que se le puede asignar a una operación estadística"
      },
      "Operation":{
         "type":"object",
         "title":"Operation",
         "allOf":[
            {
               "properties":{
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":${msg['api.doc.swagger.definitions.any.properties.kind']}
                     },
                     "description":"",
                     "type":"string"
                  },
                  "acronym":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.acronym']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "childLinks":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.childLinks']}",
                     "$ref":"#/definitions/ChildLinks"
                  },
                  "notes":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.notes']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "confidentialityDataTreatment":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.confidentialityDataTreatment']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "confidentialityPolicy":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.confidentialityPolicy']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "contact":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.contact']}",
                     "$ref":"#/definitions/Resource"
                  },
                  "currentInstance":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.currentInstance']}",
                     "$ref":"#/definitions/Resource"
                  },
                  "currentlyActive":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.currentlyActive']}",
                     "type":"boolean"
                  },
                  "dataSharings":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.dataSharings']}",
                     "$ref":"#/definitions/DataSharings"
                  },
                  "description":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.description']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.id']}",
                     "type":"string"
                  },
                  "indicatorSystem":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.indicatorSystem']}",
                     "type":"boolean"
                  },
                  "inventoryDate":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.inventoryDate']}",
                     "type":"string"
                  },
                  "legalActs":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.legalActs']}",
                     "$ref":"#/definitions/LegalActs"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.name']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "objective":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.objective']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "officialityType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.officialityType']}",
                     "$ref":"#/definitions/Item"
                  },
                  "parentLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.parentLink']}",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "producers":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.producers']}",
                     "$ref":"#/definitions/Producers"
                  },
                  "publishers":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.publishers']}",
                     "$ref":"#/definitions/Publishers"
                  },
                  "regionalContributors":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.regionalContributors']}",
                     "$ref":"#/definitions/RegionalContributors"
                  },
                  "regionalResponsibles":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.regionalResponsibles']}",
                     "$ref":"#/definitions/RegionalResponsibles"
                  },
                  "relPolUsAc":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.relPolUsAc']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "releaseCalendar":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.releaseCalendar']}",
                     "type":"boolean"
                  },
                  "releaseCalendarAccess":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.releaseCalendarAccess']}",
                     "type":"string"
                  },
                  "revPolicy":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.revPolicy']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "revPractice":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.revPractice']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "secondarySubjectAreas":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.secondarySubjectAreas']}",
                     "$ref":"#/definitions/SecondarySubjectAreas"
                  },
                  "selfLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.selfLink']}",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "statisticalOperationType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.statisticalOperationType']}",
                     "$ref":"#/definitions/Item"
                  },
                  "status":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.status']}",
                     "$ref":"#/definitions/Status"
                  },
                  "subjectArea":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.subjectArea']}",
                     "$ref":"#/definitions/Resource"
                  },
                  "updateFrequencies":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.updateFrequencies']}",
                     "$ref":"#/definitions/UpdateFrequencies"
                  },
                  "urn":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.urn']}",
                     "type":"string"
                  },
                  "genderPerspective":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.genderPerspective']}",
                     "type":"#/definitions/InternationalString"
                  }
               }
            }
         ],
         "description":"Conjunto de actividades, incluidas las preparatorias, que conducen a la obtención y/o difusión de resultados estadísticos sobre un determinado sector o tema o territorio. También se incluyen en el ámbito de esta definición los trabajos de infraestructura y de normalización estadística que posibilitan la coordinación, homogeneización e integración de las estadísticas, así como la recopilación de resultados y la confección de síntesis"
      },
      "Operations":{
         "type":"object",
         "title":"Operations",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "operation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourcesWithSubjectArea"
                  }
               }
            }
         ],
         "description":"Listado de operaciones estadísticas"
      },
      "Producers":{
         "type":"object",
         "title":"Producers",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "producer":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listado de organismos que colaboran en la producción de la estadística"
      },
      "Publishers":{
         "type":"object",
         "title":"Publishers",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "publisher":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listado de organismos que difunden los resultados de la operación estadística"
      },
      "RegionalContributors":{
         "type":"object",
         "title":"RegionalContributors",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "regionalContributor":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Organismos regionales colaboradores de la operación"
      },
      "RegionalResponsibles":{
         "type":"object",
         "title":"RegionalResponsibles",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "regionalResponsible":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Organismos regionales responsables de la operación"
      },
      "SecondarySubjectAreas":{
         "type":"object",
         "title":"SecondarySubjectAreas",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "secondarySubjectArea":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Áreas temáticas secundarias relacionadas con la operación"
      },
      "StatConcDefs":{
         "type":"object",
         "title":"StatConcDefs",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "statConcDef":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listado de conceptos que se manejan en la operación"
      },
      "StatisticalOperationSources":{
         "type":"object",
         "title":"StatisticalOperationSources",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "statisticalOperationSource":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Fuentes usadas para la elaboración de la operación estadística"
      },
      "StatisticalOperationTypes":{
         "type":"object",
         "title":"StatisticalOperationTypes",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "statisticalOperationType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Tipos de operaciones estadísticas"
      },
      "StatisticalUnits":{
         "type":"object",
         "title":"StatisticalUnits",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "statisticalUnit":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Unidades básicas de observación estadística para las que se proporcionan los datos"
      },
      "Status":{
         "type":"string",
         "title":"Status",
         "enum":[
            "PLANNING",
            "DESIGN",
            "PRODUCTION",
            "OUT_OF_PRINT"
         ],
         "description":"Estado de la operación estadística"
      },
      "TemporalGranularities":{
         "type":"object",
         "title":"TemporalGranularities",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "temporalGranularity":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Granularidades temporales que contemplan los datos de la operación estadística"
      },
      "UpdateFrequencies":{
         "type":"object",
         "title":"UpdateFrequencies",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "updateFrequency":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Frecuencias de acualización de los datos"
      },
      "ChildLinks":{
         "type":"object",
         "title":"ChildLinks",
         "allOf":[
            {
               "properties":{
                  "total":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.listBase.properties.total']}",
                     "type":"number"
                  },
                  "childLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.childLinks']}",
                     "$ref":"#/definitions/ResourceLink"
                  }
               }
            }
         ],
         "description":"Recursos a los que se puede acceder desde el presente recurso"
      },
      "InternationalString":{
         "type":"object",
         "title":"InternationalString",
         "allOf":[
            {
               "properties":{
                  "text":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.internationalString.properties.text']}",
                     "$ref":"#/definitions/LocalisedString"
                  }
               }
            }
         ],
         "description":"Texto en múltiples lenguajes"
      },
      "Item":{
         "type":"object",
         "title":"Item",
         "allOf":[
            {
               "properties":{
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.id']}",
                     "type":"string"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.item_resource.properties.name']}",
                     "$ref":"#/definitions/InternationalString"
                  }
               }
            }
         ],
         "description":""
      },
      "ListBase":{
         "type":"object",
         "title":"ListBase",
         "allOf":[
            {
               "properties":{
                  "firstLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.listBase.properties.firstLink']}",
                     "type":"string"
                  },
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.kind']}",
                     "type":"string"
                  },
                  "lastLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.listBase.properties.lastLink']}",
                     "type":"string"
                  },
                  "limit":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.listBase.properties.limit']}",
                     "type":"number"
                  },
                  "nextLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.listBase.properties.nextLink']}",
                     "type":"string"
                  },
                  "offset":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.listBase.properties.offset']}",
                     "type":"number"
                  },
                  "previousLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.listBase.properties.previousLink']}",
                     "type":"string"
                  },
                  "selfLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.listBase.properties.selfLinkExtra']}",
                     "type":"string"
                  },
                  "total":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.listBase.properties.total']}",
                     "type":"number"
                  }
               }
            }
         ],
         "description":""
      },
      "LocalisedString":{
         "type":"object",
         "title":"LocalisedString",
         "allOf":[
            {
               "properties":{
                  "lang":{
                     "xml":{
                        "attribute":true,
                        "namespace":"http://www.w3.org/XML/1998/namespace"
                     },
                     "description":"${msg['api.doc.swagger.definitions.localisedString.properties.lang']}",
                     "type":"string"
                  },
                  "(value)":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.localisedString.properties.value']}",
                     "type":"string"
                  }
               }
            }
         ],
         "description":"Texto en un idioma en particular"
      },
      "Resource":{
         "type":"object",
         "title":"Resource",
         "allOf":[
            {
               "properties":{
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.kind']}",
                     "type":"string"
                  },
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.id']}",
                     "type":"string"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.item_resource.properties.name']}",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "nestedId":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.resource.properties.nestedId']}",
                     "type":"string"
                  },
                  "selfLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.selfLink']}",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "urn":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.urn']}",
                     "type":"string"
                  }
               }
            }
         ],
         "description":""
      },
      "Resources":{
         "type":"object",
         "title":"Resources",
         "allOf":[
            {
               "properties":{
                  "total":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"number"
                  },
                  "resource":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":""
      },
      "ResourceWithSubjectArea":{
         "type":"object",
         "title":"ResourceWithSubjectArea",
         "allOf":[
            {
               "$ref":"#/definitions/Resource"
            },
            {
               "properties":{
                  "subjectArea":{
                     "description":"${msg['api.doc.swagger.definitions.operation.properties.subjectArea']}",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ]
      },
      "ResourcesWithSubjectArea":{
         "type":"object",
         "title":"ResourcesWithSubjectArea",
         "allOf":[
            {
               "properties":{
                  "total":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"number"
                  },
                  "resource":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourceWithSubjectArea"
                  }
               }
            }
         ],
         "description":""
      },
      "ResourceLink":{
         "type":"object",
         "title":"ResourceLink",
         "allOf":[
            {
               "properties":{
                  "href":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.resourceLink.properties.href']}",
                     "type":"string"
                  },
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"${msg['api.doc.swagger.definitions.any.properties.kind']}",
                     "type":"string"
                  }
               }
            }
         ],
         "description":""
      }
   },
   "paths":{
      "/v1.0/families":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.families']}"
            ],
            "description":"${msg['api.doc.swagger.paths.families.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_findFamilies_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[
               {
                  "name":"limit",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.definitions.listBase.properties.limit']}"
               },
               {
                  "name":"offset",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.definitions.listBase.properties.offset']}"
               },
               {
                  "name":"orderBy",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families_operations.get.parameters.orderBy']}"
               },
               {
                  "name":"query",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families.get.parameters.query']}"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Families"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/families/{id}":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.families']}"
            ],
            "description":"${msg['api.doc.swagger.paths.families.id.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveFamilyById_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families.id.get.parameters.id']}"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Family"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/families/{id}/operations":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.families']}"
            ],
            "description":"${msg['api.doc.swagger.paths.families.id.operations.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_findOperationsByFamily_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families.id.operations.get.parameters.id']}"
               },
               {
                  "name":"limit",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families_operations.get.parameters.limit']}"
               },
               {
                  "name":"offset",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.definitions.listBase.properties.offset']}"
               },
               {
                  "name":"orderBy",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families_operations.get.parameters.orderBy']}"
               },
               {
                  "name":"query",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.operationsQueryParam.queryDescription']}"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Operations"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/operations":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.operations']}"
            ],
            "description":"${msg['api.doc.swagger.paths.operations.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_findOperations_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[
               {
                  "name":"limit",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families_operations.get.parameters.limit']}"
               },
               {
                  "name":"offset",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.path.families_operations.get.parameters.offset']}"
               },
               {
                  "name":"orderBy",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families_operations.get.parameters.orderBy']}"
               },
               {
                  "name":"query",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.operations.operationId.instances.get.parameters.query']}"
               },
               {
                  "name":"fields",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.operations.operationId.instances.get.parameters.fields']}"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Operations"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/operations/{id}":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.operations']}"
            ],
            "description":"${msg['api.doc.swagger.paths.operations.id.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveOperationById_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.operationsIdParam.idDescription']}"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Operation"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/operations/{operationId}/instances":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.operations']}"
            ],
            "description":"${msg['api.doc.swagger.paths.operations.operationId.instances.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_findInstances_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[
               {
                  "name":"operationId",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.operationsIdParam.idDescription']}"
               },
               {
                  "name":"limit",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.definitions.listBase.properties.limit']}"
               },
               {
                  "name":"offset",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families_operations.get.parameters.offset']}"
               },
               {
                  "name":"orderBy",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.families_operations.get.parameters.orderBy']}"
               },
               {
                  "name":"query",
                  "in":"query",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.operations.operationId.instances.get.parameters.query']}"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Instances"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/operations/{operationId}/instances/{id}":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.operations']}"
            ],
            "description":"${msg['api.doc.swagger.paths.operations.operationId.instances.id.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveInstanceById_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.operations.operationId.instances.id.get.parameters.id']}"
               },
               {
                  "name":"operationId",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.operationsIdParam.idDescription']}"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Instance"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/operations/{id}/families":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.operations']}"
            ],
            "description":"${msg['api.doc.swagger.paths.operations.id.families.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveFamiliesByOperation_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.operationsIdParam.idDescription']}"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Families"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/statisticalOperationSources":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.auxiliaryValueTables']}"
            ],
            "description":"${msg['api.doc.swagger.paths.statisticalOperationSources.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveStatisticalOperationSources_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/StatisticalOperationSources"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/officialityTypes":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.auxiliaryValueTables']}"
            ],
            "description":"${msg['api.doc.swagger.paths.officialityTypes.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveOfficialityTypes_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/OfficialityTypes"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/costs":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.auxiliaryValueTables']}"
            ],
            "description":"${msg['api.doc.swagger.paths.costs.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveCosts_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Costs"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/collMethods":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.auxiliaryValueTables']}"
            ],
            "description":"${msg['api.doc.swagger.paths.collMethods.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveCollMethods_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/CollMethods"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/instanceTypes":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.auxiliaryValueTables']}"
            ],
            "description":"${msg['api.doc.swagger.paths.instanceTypes.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveInstanceTypes_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/InstanceTypes"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v1.0/statisticalOperationTypes":{
         "get":{
            "tags":[
               "${msg['api.doc.swagger.tag.auxiliaryValueTables']}"
            ],
            "description":"${msg['api.doc.swagger.paths.statisticalOperationTypes.get']}",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveStatisticalOperationTypes_GET",
            "produces":[
               "application/xml", "application/json"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/StatisticalOperationTypes"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      }
   }
}