-- --------------------------------------------------------------------------------------------------
---- EDATOS-5286 - Modificar la tabla que alimenta OFFICIALITY_TYPE para que sea jerárquica
---- Modificar tabla TB_LIS_OFFICIALITY_TYPES para que tenga una lista de valores categorizados.
--
/*
--1 Añadir extensión si no existe en el esquema extensions
--1.1) Ver si existe en esquema extensions
SELECT *
FROM pg_extension e
JOIN pg_namespace n ON e.extnamespace = n.oid
WHERE e.extname = 'uuid-ossp'
  AND n.nspname = 'extensions';
  
-- 1.2)  Si no existe crear en ese esquema

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
*/

--NOTA. Cada script se debe ejecutar dentro de un bloque para que se ejecuten secuencialmente. Si no, al tener autocommit activado el orden de inserción no tiene porqué ser el que se indica.
--------------------------------------------------------------------------------------------------------------------------


--!! ATENCIÓN!!!. PARA EJECUTAR ESTE SCRIPT PRIMERO SE HA DEBIDO EJECUTAR EL SCRIPT 1_20251006-update_tables.sql

DO $$
BEGIN
--01 Operaciones estadística oficiales
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Operaciones estadística oficiales', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Official statistical operations', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Operacions estadística oficials', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1, 0);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN

--01_01 Operaciones estadísticas de infraestructura
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Operaciones estadísticas de infraestructura', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Statistical infrastructure operations', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Operacions estadístiques d''infraestructura', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_01',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 2, 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--01_01_01 Nomenclaturas, clasificaciones y conceptos
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Nomenclaturas, clasificaciones y conceptos', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Nomenclatures, codelists and concepts', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Nomenclatures, classificacions i conceptes', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_01_01',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 3, 2);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

COMMIT;

END $$;

DO $$
BEGIN
--01_01_03 Marcos para censos o muestras
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Marcos para censos o muestras', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Frames for censuses or samples', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Marcs per a censos o mostres', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_01_03',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 4, 2);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--01_01_04 Investigación metodológica
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Investigación metodológica', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Methodological investigation', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Investigació metodològica', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_01_04',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 5, 2);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--01_01_08 Otras operaciones de infraestructura
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Otras operaciones de infraestructura', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Other infrastructure operations', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Altres operacions d''infraestructura', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_01_08',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 6, 2);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--01_02 Operaciones estadísticas propiamente dichas
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Operaciones estadísticas propiamente dichas', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Statistical operations themselves', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Operacions estadístiques pròpiament dites', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_02',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 7, 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--01_02_01 Estadísticas propiamente dichas, con resultados agregados en tablas
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estadísticas propiamente dichas, con resultados agregados en tablas', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Real statistics with results grouped in tables', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estadístiques pròpiament dites, amb resultats agregats en taules', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_02_01',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 8, 2);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--01_02_02 Estadísticas presentadas principalmente en forma de índices
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estadísticas presentadas principalmente en forma de índices', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Statistics presented mainly in the form of indexes', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estadístiques presentades principalment en forma d''índexs', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_02_02',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 9, 2);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--01_02_03 Estudios longitudinales (paneles)
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estudios longitudinales (paneles)', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Longitudinal studies (panels)', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estudis longitudinals (panells)', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_02_03',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 10, 2);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--01_03 Elaboración de síntesis y de análisis con resultados procedentes de diversas fuentes
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Elaboración de síntesis y de análisis con resultados procedentes de diversas fuentes', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Drawing up of summary and analysis with results from various sources', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Elaboració de síntesi i anàlisi amb resultats procedents de diverses fonts', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_03',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 11, 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--01_04 Recopilaciones de fuentes oficiales
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Recopilaciones de fuentes oficiales', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Compilations from official sources', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Recopilacions de fonts oficials', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'01_04',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 12, 1);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--02 Estudios estadísticos
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estudios estadísticos', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Statistical studies', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estudis estadístics', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'02',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 13, 0);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

DO $$
BEGIN
--03 Estadísticas experimentales
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estadísticas experimentales', 'es', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Experimental statistics', 'en', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (GET_NEXT_SEQUENCE_VALUE('L10NSTRS'), 'Estadístiques experimentals', 'ca', GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 1);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'L10NSTRS';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION, DESCRIPTION, VISUALISATION_ORDER, HIERARCHY_LEVEL) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'03',extensions.uuid_generate_v4(),0, GET_NEXT_SEQUENCE_VALUE('I18NSTRS'), 14, 0);

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'I18NSTRS';

END $$;

COMMIT;

