-- ----------------------------------------------------------------------------------------------------------------------------
-- EDATOS-5211 - Cambiar la etiqueta del metadato INFORMATION_SUPPLIERS y crear un nuevo metadato INFORMATION_SUPPLIERS_PRIVATE
-- ----------------------------------------------------------------------------------------------------------------------------

-- Rename table TB_EI_PUBLIC_INF_SUPPLIERS to TB_EI_PUBLIC_INF_SUPPLIERS

-- Drop existing constraints
ALTER TABLE TB_EI_INF_SUPPLIERS DROP CONSTRAINT FK_TB_EI_INF_SUPPLIERS_INFORMATION_SUPPLIERS_FK;
ALTER TABLE TB_EI_INF_SUPPLIERS DROP CONSTRAINT FK_TB_EI_INF_SUPPLIERS_TB_INSTANCES;
ALTER TABLE TB_EI_INF_SUPPLIERS DROP CONSTRAINT PK_TB_EI_INF_SUPPLIERS;

-- Rename the table
ALTER TABLE TB_EI_INF_SUPPLIERS RENAME TO TB_EI_PUBLIC_INF_SUPPLIERS;

-- Rename the column
ALTER TABLE TB_EI_PUBLIC_INF_SUPPLIERS RENAME COLUMN INFORMATION_SUPPLIERS_FK TO PUBLIC_INF_SUPPLIERS_FK;

-- Recreate primary key constraint with new name
ALTER TABLE TB_EI_PUBLIC_INF_SUPPLIERS ADD CONSTRAINT PK_TB_EI_PUBLIC_INF_SUPPLIERS
    PRIMARY KEY (PUBLIC_INF_SUPPLIERS_FK, TB_INSTANCES);

-- Recreate foreign key constraints with new names
ALTER TABLE TB_EI_PUBLIC_INF_SUPPLIERS ADD CONSTRAINT FK_TB_EI_PUBLIC_INF_SUPPLIERS_PUBLIC_INF_SUPPLIERS_FK
    FOREIGN KEY (PUBLIC_INF_SUPPLIERS_FK) REFERENCES TB_EXTERNAL_ITEMS (ID);

ALTER TABLE TB_EI_PUBLIC_INF_SUPPLIERS ADD CONSTRAINT FK_TB_EI_PUBLIC_INF_SUPPLIERS_TB_INSTANCES
    FOREIGN KEY (TB_INSTANCES) REFERENCES TB_INSTANCES (ID);

commit;
